# Uncomment the next line to define a global platform for your project
platform :ios, ‘9.0’

use_frameworks!
inhibit_all_warnings!

target 'TNCalendarApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks


  # Pods for TNCalendarApp
pod 'RxSwift',    '~> 4.0'
pod 'RxCocoa',    '~> 4.0'
pod 'RxDataSources', '~> 3.0'
pod 'BmobSDK'
pod 'SnapKit', '~> 4.0.0'
pod 'SwiftyJSON'
pod 'IQKeyboardManagerSwift'
pod 'ImagePicker', '~> 3.0.0'
pod 'Lightbox'
pod 'Hue'
pod 'PKHUD', '~> 5.0'

end
