# Uncomment the next line to define a global platform for your project
platform :ios, ‘8.0’

target 'TNCalendarApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TNCalendarApp
pod 'RxSwift',    '~> 4.0'
pod 'RxCocoa',    '~> 4.0'
pod 'RxDataSources', '~> 3.0'
pod 'BmobSDK'
pod 'SnapKit', '~> 4.0.0'
pod 'SwiftyJSON'
pod 'IQKeyboardManagerSwift'

end
